class Blog {
  String imgurl;
  String imgurl2;
  String heading;
  String subtitle;
  String sh1;
  String c1;
  String sh2;
  String c2;
  String sh3;
  String c3;
  String sh4;
  String c4;
  String sh5;
  String c5;
  String sh6;
  String c6;
  String sh7;
  String c7;
  String sh8;
  String c8;
  String sh9;
  String c9;
  String sh10;
  String c10;
  String sh11;
  String c11;
  String sh12;
  String c12;

  Blog(
      {
        required this.imgurl2,
        required this.imgurl,
      required this.heading,
      required this.subtitle,
      required this.sh1,
      required this.c1,
      required this.sh2,
      required this.c2,
      required this.sh3,
      required this.c3,
      required this.sh4,
      required this.c4,
      required this.sh5,
      required this.c5,
      required this.sh6,
      required this.c6,
      required this.sh7,
      required this.c7,
      required this.sh8,
      required this.c8,
      required this.sh9,
      required this.c9,
      required this.sh10,
      required this.c10,
      required this.sh11,
      required this.c11,
      required this.sh12,
      required this.c12});
}
